### ISSUE TITLE
Home page visuals

### ISSUE THREAD

**Issue by jordan2lee** [bmeg/bmeg-dash#24]
- [x] Task: add icons for Home page widget cards  ?

- [x] Task: clean up looks of Home page

**Comment by jordan2lee** [comment]
addressed in PR #33 

decided to not add icons to widgets. 

work on branch `home-visuals`

**Comment by kellrott** [comment]
The main page card build should probably be done procedurally, based on a config file, rather then card coded.

**Comment by jordan2lee** [comment]
addressed in merged PRs
